# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: threat_detection/message/http_response_param/v1/http_response_param.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'threat_detection/message/http_response_param/v1/http_response_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIthreat_detection/message/http_response_param/v1/http_response_param.proto\x12/threat_detection.message.http_response_param.v1\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xf9\x06\n\x11HttpResponseParam\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x7f\n\x0frequest_headers\x18\x04 \x03(\x0b\x32V.threat_detection.message.http_response_param.v1.HttpResponseParam.RequestHeadersEntryR\x0erequestHeaders\x12\'\n\x0frequest_payload\x18\x05 \x01(\tR\x0erequestPayload\x12*\n\x11\x61pi_collection_id\x18\x06 \x01(\x05R\x0f\x61piCollectionId\x12\x1f\n\x0bstatus_code\x18\x07 \x01(\x05R\nstatusCode\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x82\x01\n\x10response_headers\x18\t \x03(\x0b\x32W.threat_detection.message.http_response_param.v1.HttpResponseParam.ResponseHeadersEntryR\x0fresponseHeaders\x12)\n\x10response_payload\x18\n \x01(\tR\x0fresponsePayload\x12\x0c\n\x04time\x18\x0b \x01(\x05\x12\x17\n\x0f\x61kto_account_id\x18\x0c \x01(\t\x12\n\n\x02ip\x18\r \x01(\t\x12\x17\n\x07\x64\x65st_ip\x18\x0e \x01(\tR\x06\x64\x65stIp\x12\x11\n\tdirection\x18\x0f \x01(\t\x12\x12\n\nis_pending\x18\x10 \x01(\x08\x12\x0e\n\x06source\x18\x11 \x01(\t\x12\x15\n\rakto_vxlan_id\x18\x12 \x01(\t\x1ar\n\x13RequestHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12J\n\x05value\x18\x02 \x01(\x0b\x32;.threat_detection.message.http_response_param.v1.StringList:\x02\x38\x01\x1as\n\x14ResponseHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12J\n\x05value\x18\x02 \x01(\x0b\x32;.threat_detection.message.http_response_param.v1.StringList:\x02\x38\x01\x42<B\x16HttpResponseParamProtoZ\"protobuf/traffic_payload;trafficpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'threat_detection.message.http_response_param.v1.http_response_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\026HttpResponseParamProtoZ\"protobuf/traffic_payload;trafficpb'
  _globals['_HTTPRESPONSEPARAM_REQUESTHEADERSENTRY']._loaded_options = None
  _globals['_HTTPRESPONSEPARAM_REQUESTHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_HTTPRESPONSEPARAM_RESPONSEHEADERSENTRY']._loaded_options = None
  _globals['_HTTPRESPONSEPARAM_RESPONSEHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_STRINGLIST']._serialized_start=126
  _globals['_STRINGLIST']._serialized_end=154
  _globals['_HTTPRESPONSEPARAM']._serialized_start=157
  _globals['_HTTPRESPONSEPARAM']._serialized_end=1046
  _globals['_HTTPRESPONSEPARAM_REQUESTHEADERSENTRY']._serialized_start=815
  _globals['_HTTPRESPONSEPARAM_REQUESTHEADERSENTRY']._serialized_end=929
  _globals['_HTTPRESPONSEPARAM_RESPONSEHEADERSENTRY']._serialized_start=931
  _globals['_HTTPRESPONSEPARAM_RESPONSEHEADERSENTRY']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
