# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: threat_detection/message/malicious_event/event_type/v1/event_type.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'threat_detection/message/malicious_event/event_type/v1/event_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGthreat_detection/message/malicious_event/event_type/v1/event_type.proto\x12\x36threat_detection.message.malicious_event.event_type.v1*Y\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x45VENT_TYPE_SINGLE\x10\x01\x12\x19\n\x15\x45VENT_TYPE_AGGREGATED\x10\x02\x42M\n6threat_detection.message.malicious_event.event_type.v1B\x13MaliciousEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'threat_detection.message.malicious_event.event_type.v1.event_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n6threat_detection.message.malicious_event.event_type.v1B\023MaliciousEventProto'
  _globals['_EVENTTYPE']._serialized_start=131
  _globals['_EVENTTYPE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
