# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: threat_detection/message/malicious_event/v1/message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'threat_detection/message/malicious_event/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akto_proto.threat_detection.message.malicious_event.event_type.v1 import event_type_pb2 as threat__detection_dot_message_dot_malicious__event_dot_event__type_dot_v1_dot_event__type__pb2
from akto_proto.threat_detection.message.sample_request.v1 import message_pb2 as threat__detection_dot_message_dot_sample__request_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9threat_detection/message/malicious_event/v1/message.proto\x12+threat_detection.message.malicious_event.v1\x1aGthreat_detection/message/malicious_event/event_type/v1/event_type.proto\x1a\x38threat_detection/message/sample_request/v1/message.proto\"O\n\rOwaspCategory\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\t\"\x8d\x05\n\x15MaliciousEventMessage\x12\r\n\x05\x61\x63tor\x18\x01 \x01(\t\x12\x11\n\tfilter_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65tected_at\x18\x03 \x01(\x03\x12\x15\n\rlatest_api_ip\x18\x04 \x01(\t\x12\x1b\n\x13latest_api_endpoint\x18\x05 \x01(\t\x12\x19\n\x11latest_api_method\x18\x06 \x01(\t\x12 \n\x18latest_api_collection_id\x18\x07 \x01(\x05\x12\x1a\n\x12latest_api_payload\x18\x08 \x01(\t\x12U\n\nevent_type\x18\t \x01(\x0e\x32\x41.threat_detection.message.malicious_event.event_type.v1.EventType\x12\x10\n\x08\x63\x61tegory\x18\n \x01(\t\x12\x14\n\x0csub_category\x18\x0b \x01(\t\x12\x10\n\x08severity\x18\x0c \x01(\t\x12\x0c\n\x04type\x18\r \x01(\t\x12\x46\n\x08metadata\x18\x0e \x01(\x0b\x32\x34.threat_detection.message.sample_request.v1.Metadata\x12\x1a\n\x12successful_exploit\x18\x0f \x01(\x08\x12\r\n\x05label\x18\x10 \x01(\t\x12\x0c\n\x04host\x18\x11 \x01(\t\x12\x0e\n\x06status\x18\x12 \x01(\t\x12\x16\n\x0e\x63ontext_source\x18\x13 \x01(\t\x12\x12\n\nsession_id\x18\x14 \x01(\t\x12T\n\x10owasp_categories\x18\x15 \x03(\x0b\x32:.threat_detection.message.malicious_event.v1.OwaspCategory\"\x9d\x01\n\x1bMaliciousEventKafkaEnvelope\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x02 \x01(\t\x12[\n\x0fmalicious_event\x18\x03 \x01(\x0b\x32\x42.threat_detection.message.malicious_event.v1.MaliciousEventMessageBB\n+threat_detection.message.malicious_event.v1B\x13MaliciousEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'threat_detection.message.malicious_event.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+threat_detection.message.malicious_event.v1B\023MaliciousEventProto'
  _globals['_OWASPCATEGORY']._serialized_start=237
  _globals['_OWASPCATEGORY']._serialized_end=316
  _globals['_MALICIOUSEVENTMESSAGE']._serialized_start=319
  _globals['_MALICIOUSEVENTMESSAGE']._serialized_end=972
  _globals['_MALICIOUSEVENTKAFKAENVELOPE']._serialized_start=975
  _globals['_MALICIOUSEVENTKAFKAENVELOPE']._serialized_end=1132
# @@protoc_insertion_point(module_scope)
